---
title: "R Notebook"
output: html_notebook
---

# Import needed libraries

```{r}
#PACKAGES NEEDED
rm(list=ls())
library(dplyr)
library(ggplot2)
library (readr)
```

# Import data from source

```{r}
# Original dataset of PROPUBLICA (from their GitHub)
urlfile = "https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv"
raw_data <- read_csv(url(urlfile))
```
# Basic Exploration

```{r}
# Look at the dataset
nrow(raw_data)
```
```{r}
head(raw_data)
```

```{r}
# What are the unique values of variable 'race'?
unique(raw_data$race)
```


```{r}
# What about its distribution?
table(raw_data$race)
```


```{r}
# What are the available variables?
colnames(raw_data)
```

# Data Transformation

```{r}
# Transforming some variables 

# According to the company that developed COMPAS, a person should be
# considered at risk of recidivism if the algorithm classifies him/her
# as MEDIUM RISK or HIGH RISK
raw_data$target = ifelse(raw_data$score_text == 'Medium' |
                           raw_data$score_text == 'High',
                         'At risk',
                         'No risk')
# F=felony, M=misdemeanor
raw_data$charge_degree = ifelse(raw_data$c_charge_degree == 'F', 1, 0)
raw_data$age_cat = ifelse(raw_data$age_cat == 'Less than 25', 1, 0)
```

```{r}
# Keeping only variables of interest (i.e. anonymize the data)

# Also, drop values of is_recid = -1 because that means there is no COMPAS record
# The variable is_recid indicates people for which a 'RECIDIVIST FLAG' is on

# I only kept people with variable race = Caucasian or African American

df <-
  dplyr::select(
    raw_data,
    sex,
    age,
    race,
    juv_fel_count,
    decile_score,
    juv_misd_count,
    juv_other_count,
    priors_count,
    is_recid,
    charge_degree,
    score_text,
    two_year_recid,
    target,
  ) %>% filter(is_recid != -1) %>%
  filter(charge_degree != "O") %>%
  filter(target != 'N/A') %>% filter(race != 'Asian') %>% filter(race !=
                                                                   'Hispanic') %>% filter(race != 'Native American') %>% filter(race != 'Other')
head(df)
```

```{r}
nrow(df)
```
```{r}
table(df$race)
```


```{r}
# Selecting final variables for training
df <-
  dplyr::select(
    df,
    sex,
    age,
    race,
    juv_fel_count,
    juv_misd_count,
    juv_other_count,
    priors_count,
    charge_degree,
    target,
    two_year_recid
  )
head(df)
```

```{r}
# Further data transformation
df$sex=ifelse(df$sex=='Male', 1, 0)
df$race=ifelse(df$race=='Caucasian', 1, 0)
df$target=ifelse(df$target=='At risk', 1, 0)
```


```{r}
head(df)
```
# Data Exploration

```{r}
# EXPLORATORY 
df$race = as.factor(df$race)
ggplot(df, aes(x = priors_count)) +
  geom_histogram(aes(color = race, fill = race),position = "identity", bins = 30, alpha = 0.4) +
  scale_color_manual(values = c("indianred1", "lightskyblue1")) +
  scale_fill_manual(values = c("indianred1", "lightskyblue1")) + ggtitle("Distribution of PRIORS COUNT by race") 

```

```{r}
charge_by_race_c1 = sum(df$charge_degree==1&df$race==1)
charge_by_race_c0 = sum(df$charge_degree==0&df$race==1)
charge_by_race_a1 = sum(df$charge_degree==1&df$race==0)
charge_by_race_a0 = sum(df$charge_degree==0&df$race==0)
data <- data.frame(c(charge_by_race_a1,charge_by_race_a0, charge_by_race_c1, charge_by_race_c0))
data$charge = c(1,0,1,0)
data$race = c(0,0,1,1)
names(data)[names(data) == "c.charge_by_race_a1..charge_by_race_a0..charge_by_race_c1..charge_by_race_c0."] <- "Counts"
head(data)
```



```{r}
# Bar plots
data$charge = as.factor(data$charge)
data$race = as.factor(data$race)
ggplot(data, aes(x = charge, y = Counts)) +
  geom_bar(
    aes(color = race, fill = race),
    stat = "identity", position = position_dodge(0.8),
    width = 0.7
    )  +
   xlab( "Charge (0 = Misdemeanour, 1 = Felony)")+
  scale_color_manual(values = c("indianred1", "lightskyblue1"))+
  scale_fill_manual(values = c("indianred1", "lightskyblue1"))+  ggtitle("Distribution of CHARGE DEGREE by race (0 = black, 1 = white)")

```

# Generate csv

```{r}
# Create csv to be imported in Python
# This is the csv present in the "data" folder
write.csv(df,'data.csv',row.names = FALSE)
```

